name: iraq_location_picker
description: Enhanced location picker for Iraqi governorates with interactive map functionality and traditional dropdown selection.
version: 0.1.0
repository: https://github.com/anasjasim/iraq-location-picker
homepage: https://github.com/anasjasim/iraq-location-picker
documentation: https://github.com/anasjasim/iraq-location-picker
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/data/iraq_governorates.json
    - lib/data/iraq_geo_location_adm1.json
